### ISSUE TITLE
依赖版本不要写死

### ISSUE THREAD

**Issue by luozhouyang** [PyUnit/pyunit-sogou#1]
`requirements`里面声明的依赖不要写死。目前在一个地方使用了本库，但是因为本库的依赖写死，报警：依赖版本不兼容。

解决方法就是把`requirements`里面的依赖版本去掉。

**Comment by jtyoui** [comment]
> `requirements`里面声明的依赖不要写死。目前在一个地方使用了本库，但是因为本库的依赖写死，报警：依赖版本不兼容。
> 
> 解决方法就是把`requirements`里面的依赖版本去掉。

不写依赖版本是不行的，因为我需要它的组件。如果不写他的组件版本，万一他的组件修改了该功能或者去掉的该功能，那我的组件也随之失效。如果你遇到安装依赖冲突，请试做跳过安装冲突的依赖，安装办法是 ``` pip install xx --no-dependencies ``` 。忽略安装的依赖的版本限制。不建议这样使用，最好用 ```virtualenv``` 环境来单独创建一个项目。

**Comment by luozhouyang** [comment]
这些知名的库基本上是保证向前兼容的，而且你用到的API都是非常常见的API，基本上不会出现这个问题。我是使用conda创建的虚拟环境，但是有些其他库也依赖的库报警告。
